# Generated by Django 4.1.5 on 2023-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainappReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mainApp_review',
                'managed': False,
            },
        ),
    ]
