# Generated by Django 4.1.5 on 2023-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test01',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mainApp_review',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MainappReview',
        ),
    ]
