# Generated by Django 4.1.5 on 2023-01-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0002_test01_delete_mainappreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
    ]
