# Generated by Django 4.1.5 on 2023-01-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0003_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test01',
        ),
    ]
